modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
issueTrackerURL="https://github.com/Tagnum-Mods/Complex-Colonists/issues"

[[mods]]
modId="complexcolonists"
version="${file.jarVersion}"
displayName="Complex Colonists"
#updateJSONURL="https://github.com/Tagnum-Mods/Complex-Colonists/updates.json"
displayURL="https://github.com/Tagnum-Mods/Complex-Colonists"
logoFile="complex-colonists.png"
credits="Thanks to the LDTTeam for the awesome Minecolonies mod!"
authors="TagnumElite"
description='''
A mod that adds more jobs and buildings for your colonists to take on!

Tested Versions:
- Forge: ${mc_version}-${forge_version}
- Minecolonies: ${minecolonies_version}
- BlockUI: ${blockui_version}
- Domum Oranentum: ${domum_ornamentum_version}
- Multi-Piston: ${multi_piston_version}
- Structurize: ${structurize_version}
'''

#[[dependencies.complexcolonists]]
#    modId="minecolonies"
#    mandatory=true
#    versionRange="[${minecolonies_version},)"
#    ordering="NONE"
#    side="BOTH"

[[dependencies.complexcolonists]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.complexcolonists]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
