modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
issueTrackerURL="https://github.com/Tagnum-Mods/Complex-Colonists/issues"

[[mods]]
modId="complexcolonists"
version="${file.jarVersion}"
displayName="Complex Colonists"
#updateJSONURL="https://github.com/Tagnum-Mods/Complex-Colonists/updates.json"
displayURL="https://github.com/Tagnum-Mods/Complex-Colonists"
logoFile="complex-colonists.png"
credits="Thanks to the LDTTeam for the awesome Minecolonies mod!"
authors="TagnumElite"
description='''A mod that adds more jobs and buildings for your colonists to take on!'''

#[[dependencies.complexcolonists]]
#    modId="minecolonies"
#    mandatory=true
#    versionRange="[${minecolonies_version},)"
#    ordering="NONE"
#    side="BOTH"

[[dependencies.complexcolonists]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.complexcolonists]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
