modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Tagnum-Mods/Complex-Colonists/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
#updateJSONURL="https://github.com/Tagnum-Mods/Complex-Colonists/updates.json"
displayURL="https://github.com/Tagnum-Mods/Complex-Colonists"
logoFile="complex-colonists.png"
credits="Thanks to the LDTTeam for the awesome Minecolonies mod!"
authors="${mod_authors}"
description='''${mod_description}

Tested Versions:
- Forge: ${minecraft_version}-${forge_version}
- Minecolonies: ${minecolonies_version}
- BlockUI: ${blockui_version}
- Domum Oranentum: ${domum_ornamentum_version}
- Multi-Piston: ${multipiston_version}
- Structurize: ${structurize_version}
'''

#[[dependencies.${mod_id}]]
#    modId="minecolonies"
#    mandatory=true
#    versionRange="${minecolonies_version_range}"
#    ordering="NONE"
#    side="BOTH"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
